import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cta_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_pages_blocks_cta_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_pages_blocks_cta_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_pages_blocks_content_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_pages_blocks_content_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_pages_blocks_content_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_pages_blocks_media_block_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_pages_blocks_media_block_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_pages_blocks_media_block_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_pages_blocks_archive_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_pages_blocks_archive_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_pages_blocks_archive_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_pages_blocks_form_block_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_pages_blocks_form_block_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_pages_blocks_form_block_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__pages_v_blocks_content_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__pages_v_blocks_content_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__pages_v_blocks_content_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_service_pages_blocks_cta_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_service_pages_blocks_cta_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_service_pages_blocks_cta_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_service_pages_blocks_content_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_service_pages_blocks_content_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_service_pages_blocks_content_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum_service_pages_blocks_media_block_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum_service_pages_blocks_media_block_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum_service_pages_blocks_media_block_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__service_pages_v_blocks_cta_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__service_pages_v_blocks_cta_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__service_pages_v_blocks_cta_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__service_pages_v_blocks_content_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__service_pages_v_blocks_content_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__service_pages_v_blocks_content_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  CREATE TYPE "public"."enum__service_pages_v_blocks_media_block_settings_font_family" AS ENUM('inherit', '''Inter'', sans-serif', '''Playfair Display'', serif', '''Space Grotesk'', sans-serif', '''Montserrat'', sans-serif', '''Roboto Mono'', monospace');
  CREATE TYPE "public"."enum__service_pages_v_blocks_media_block_settings_font_weight" AS ENUM('300', '400', '500', '600', '700', '900');
  CREATE TYPE "public"."enum__service_pages_v_blocks_media_block_settings_bg_image_fit" AS ENUM('cover', 'contain', 'fill');
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_font_family" "enum_pages_blocks_cta_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_font_weight" "enum_pages_blocks_cta_settings_font_weight" DEFAULT '400';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_bg_image_fit" "enum_pages_blocks_cta_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_font_family" "enum_pages_blocks_content_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_font_weight" "enum_pages_blocks_content_settings_font_weight" DEFAULT '400';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_bg_image_fit" "enum_pages_blocks_content_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_font_family" "enum_pages_blocks_media_block_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_font_weight" "enum_pages_blocks_media_block_settings_font_weight" DEFAULT '400';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_bg_image_fit" "enum_pages_blocks_media_block_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_font_family" "enum_pages_blocks_archive_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_font_weight" "enum_pages_blocks_archive_settings_font_weight" DEFAULT '400';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_bg_image_fit" "enum_pages_blocks_archive_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_font_family" "enum_pages_blocks_form_block_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_font_weight" "enum_pages_blocks_form_block_settings_font_weight" DEFAULT '400';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_bg_image_fit" "enum_pages_blocks_form_block_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_font_family" "enum__pages_v_blocks_cta_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_font_weight" "enum__pages_v_blocks_cta_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_bg_image_fit" "enum__pages_v_blocks_cta_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_font_family" "enum__pages_v_blocks_content_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_font_weight" "enum__pages_v_blocks_content_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_bg_image_fit" "enum__pages_v_blocks_content_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_font_family" "enum__pages_v_blocks_media_block_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_font_weight" "enum__pages_v_blocks_media_block_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_bg_image_fit" "enum__pages_v_blocks_media_block_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_font_family" "enum__pages_v_blocks_archive_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_font_weight" "enum__pages_v_blocks_archive_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_bg_image_fit" "enum__pages_v_blocks_archive_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_font_family" "enum__pages_v_blocks_form_block_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_font_weight" "enum__pages_v_blocks_form_block_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_bg_image_fit" "enum__pages_v_blocks_form_block_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_font_family" "enum_service_pages_blocks_cta_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_font_weight" "enum_service_pages_blocks_cta_settings_font_weight" DEFAULT '400';
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_bg_image_fit" "enum_service_pages_blocks_cta_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "service_pages_blocks_cta" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_font_family" "enum_service_pages_blocks_content_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_font_weight" "enum_service_pages_blocks_content_settings_font_weight" DEFAULT '400';
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_bg_image_fit" "enum_service_pages_blocks_content_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "service_pages_blocks_content" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_font_family" "enum_service_pages_blocks_media_block_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_font_weight" "enum_service_pages_blocks_media_block_settings_font_weight" DEFAULT '400';
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_bg_image_fit" "enum_service_pages_blocks_media_block_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "service_pages_blocks_media_block" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_font_family" "enum__service_pages_v_blocks_cta_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_font_weight" "enum__service_pages_v_blocks_cta_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_bg_image_fit" "enum__service_pages_v_blocks_cta_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_service_pages_v_blocks_cta" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_font_family" "enum__service_pages_v_blocks_content_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_font_weight" "enum__service_pages_v_blocks_content_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_bg_image_fit" "enum__service_pages_v_blocks_content_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_service_pages_v_blocks_content" ADD COLUMN "settings_custom_code" varchar;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_font_family" "enum__service_pages_v_blocks_media_block_settings_font_family" DEFAULT 'inherit';
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_font_weight" "enum__service_pages_v_blocks_media_block_settings_font_weight" DEFAULT '400';
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_font_size" numeric;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_color_background" varchar;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_color_text" varchar;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_color_accent" varchar;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_padding_top" numeric;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_padding_bottom" numeric;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_bg_image_url" varchar;
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_bg_image_fit" "enum__service_pages_v_blocks_media_block_settings_bg_image_fit" DEFAULT 'cover';
  ALTER TABLE "_service_pages_v_blocks_media_block" ADD COLUMN "settings_custom_code" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_font_family";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_font_weight";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_font_size";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_color_background";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_color_text";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_color_accent";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_padding_top";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "settings_custom_code";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_font_family";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_font_weight";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_font_size";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_color_background";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_color_text";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_color_accent";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_padding_top";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "settings_custom_code";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_font_family";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_font_weight";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_font_size";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_color_background";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_color_text";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_color_accent";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_padding_top";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "settings_custom_code";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_font_family";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_font_weight";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_font_size";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_color_background";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_color_text";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_color_accent";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_padding_top";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "settings_custom_code";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_font_family";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_font_weight";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_font_size";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_color_background";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_color_text";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_color_accent";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_padding_top";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_font_family";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_font_size";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_color_background";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_color_text";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_font_family";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_font_size";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_color_background";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_color_text";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_font_family";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_font_size";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_color_background";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_color_text";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_font_family";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_font_size";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_color_background";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_color_text";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_font_family";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_font_size";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_color_background";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_color_text";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "settings_custom_code";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_font_family";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_font_weight";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_font_size";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_color_background";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_color_text";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_color_accent";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_padding_top";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "service_pages_blocks_cta" DROP COLUMN "settings_custom_code";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_font_family";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_font_weight";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_font_size";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_color_background";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_color_text";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_color_accent";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_padding_top";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "service_pages_blocks_content" DROP COLUMN "settings_custom_code";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_font_family";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_font_weight";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_font_size";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_color_background";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_color_text";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_color_accent";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_padding_top";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "service_pages_blocks_media_block" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_font_family";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_font_size";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_color_background";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_color_text";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_service_pages_v_blocks_cta" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_font_family";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_font_size";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_color_background";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_color_text";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_service_pages_v_blocks_content" DROP COLUMN "settings_custom_code";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_font_family";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_font_weight";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_font_size";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_color_background";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_color_text";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_color_accent";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_padding_top";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_padding_bottom";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_bg_image_url";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_bg_image_fit";
  ALTER TABLE "_service_pages_v_blocks_media_block" DROP COLUMN "settings_custom_code";
  DROP TYPE "public"."enum_pages_blocks_cta_settings_font_family";
  DROP TYPE "public"."enum_pages_blocks_cta_settings_font_weight";
  DROP TYPE "public"."enum_pages_blocks_cta_settings_bg_image_fit";
  DROP TYPE "public"."enum_pages_blocks_content_settings_font_family";
  DROP TYPE "public"."enum_pages_blocks_content_settings_font_weight";
  DROP TYPE "public"."enum_pages_blocks_content_settings_bg_image_fit";
  DROP TYPE "public"."enum_pages_blocks_media_block_settings_font_family";
  DROP TYPE "public"."enum_pages_blocks_media_block_settings_font_weight";
  DROP TYPE "public"."enum_pages_blocks_media_block_settings_bg_image_fit";
  DROP TYPE "public"."enum_pages_blocks_archive_settings_font_family";
  DROP TYPE "public"."enum_pages_blocks_archive_settings_font_weight";
  DROP TYPE "public"."enum_pages_blocks_archive_settings_bg_image_fit";
  DROP TYPE "public"."enum_pages_blocks_form_block_settings_font_family";
  DROP TYPE "public"."enum_pages_blocks_form_block_settings_font_weight";
  DROP TYPE "public"."enum_pages_blocks_form_block_settings_bg_image_fit";
  DROP TYPE "public"."enum__pages_v_blocks_cta_settings_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_cta_settings_font_weight";
  DROP TYPE "public"."enum__pages_v_blocks_cta_settings_bg_image_fit";
  DROP TYPE "public"."enum__pages_v_blocks_content_settings_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_content_settings_font_weight";
  DROP TYPE "public"."enum__pages_v_blocks_content_settings_bg_image_fit";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_settings_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_settings_font_weight";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_settings_bg_image_fit";
  DROP TYPE "public"."enum__pages_v_blocks_archive_settings_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_archive_settings_font_weight";
  DROP TYPE "public"."enum__pages_v_blocks_archive_settings_bg_image_fit";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_settings_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_settings_font_weight";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_settings_bg_image_fit";
  DROP TYPE "public"."enum_service_pages_blocks_cta_settings_font_family";
  DROP TYPE "public"."enum_service_pages_blocks_cta_settings_font_weight";
  DROP TYPE "public"."enum_service_pages_blocks_cta_settings_bg_image_fit";
  DROP TYPE "public"."enum_service_pages_blocks_content_settings_font_family";
  DROP TYPE "public"."enum_service_pages_blocks_content_settings_font_weight";
  DROP TYPE "public"."enum_service_pages_blocks_content_settings_bg_image_fit";
  DROP TYPE "public"."enum_service_pages_blocks_media_block_settings_font_family";
  DROP TYPE "public"."enum_service_pages_blocks_media_block_settings_font_weight";
  DROP TYPE "public"."enum_service_pages_blocks_media_block_settings_bg_image_fit";
  DROP TYPE "public"."enum__service_pages_v_blocks_cta_settings_font_family";
  DROP TYPE "public"."enum__service_pages_v_blocks_cta_settings_font_weight";
  DROP TYPE "public"."enum__service_pages_v_blocks_cta_settings_bg_image_fit";
  DROP TYPE "public"."enum__service_pages_v_blocks_content_settings_font_family";
  DROP TYPE "public"."enum__service_pages_v_blocks_content_settings_font_weight";
  DROP TYPE "public"."enum__service_pages_v_blocks_content_settings_bg_image_fit";
  DROP TYPE "public"."enum__service_pages_v_blocks_media_block_settings_font_family";
  DROP TYPE "public"."enum__service_pages_v_blocks_media_block_settings_font_weight";
  DROP TYPE "public"."enum__service_pages_v_blocks_media_block_settings_bg_image_fit";`)
}
